### ISSUE TITLE
Open Source Checklist

### ISSUE THREAD

**Issue by IMB11** [moddedmc-wiki/fabric-modding-wiki#22]
Before I can open source the repo, the following needs to be done (in order)

- [x] Partially Finish Block Guides
- [x] Proofread all pages
- [x] Generate codeowners file(s)
- [x] Setup PR actions
- [x] Setup Branch Protection for `master`

- Rename master to main?
